baseurl                  = "https://shkero.github.io/xenoblade/"           # Your domain name
languageCode             = "zh-CN"
defaultContentLanguage   = "zh"
isMultilingual           = false
title                    = "Xenoblade"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "Nothing is true,everything is permitted."

# Metadata for Open Graph and Twitter
    description          = "Xenoblade"               # Max 160 characters show in search results
    images               = ["tn.png"]                # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Han"
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "/sample_video.mp4"
    type    = "video/mp4"
    poster  = "/background.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional
    
[[params.mainMenu]]
    link = "posts"
    text = "随笔"

[[params.mainMenu]]
    link = "wallpaper"
    text = "图片"

[[params.mainMenu]]
    link = "about"
    text = "无言"

[imaging]
    quality = 75
